networks:
  apitemplate-backend:
    name: apitemplate-backend

services:
  apitemplate.redis:
    container_name: redis
    image: redis:latest
    ports:
      - 8003:6379
    networks:
      - apitemplate-backend
  apitemplate.db:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    image: postgres:latest
    restart: always
    volumes:
      - appdata:/var/lib/postgresql/data
    ports:
      - 8002:5432
    networks:
      - apitemplate-backend
  apitemplate.api:
    container_name: apitemplate.api
    image: apitemplate.api
    build:
      context: .
      dockerfile: src/apitemplate.Api/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://*:80
        - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=postgres;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
        - ConnectionStrings__Redis=redis:6379
        - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
        - JwtSettings__ExpiryMinutes=1
        - JwtSettings__Issuer=ApiTemplate
        - JwtSettings__Audience=ApiTemplate
    ports:
      - 8001:80
    depends_on:
      - apitemplate.db
      - apitemplate.redis
    networks:
      - apitemplate-backend

volumes: 
  appdata:
    